const fileInput = document.getElementById('fileInput');
const codeInput = document.getElementById('codeInput');
const analyzeBtn = document.getElementById('analyzeBtn');
const resultContainer = document.getElementById('resultContainer');
const summary = document.getElementById('summary');
const dangerList = document.getElementById('dangerList');

// 危険なコードパターン（拡張可）
const dangerPatterns = [
  /eval\s*\(/i,
  /exec\s*\(/i,
  /os\.system\s*\(/i,
  /Runtime\.getRuntime\(\)\.exec/i,
  /ProcessBuilder/i,
  /child_process\.exec/i,
  /child_process\.spawn/i,
  /subprocess\.Popen/i,
  /document\.write\s*\(/i,
  /innerHTML\s*=/i,
  /fs\.(writeFile|unlink|readdir|rmdir|readFile|appendFile)/i,
  /require\(['"]child_process['"]\)/i,
  /SetSecurityManager/i,
  /system\s*\(/i,
  /shell_exec/i,
  /popen\s*\(/i,
  /CreateObject\("WScript\.Shell"\)/i,
  /powershell\s*-NoProfile/i,
  /`.*?`/, // Shellバッククオート
  /\bLOAD\b.*\bDATA\b/i,
  /DROP\s+TABLE/i,
  /<script[\s>]/i,
  /base64\s*,/i
];


// 拡張子と対応言語のDB（必要に応じて増やせる）
const langMap = {
  ".js": "JavaScript", ".mjs": "JavaScript", ".cjs": "JavaScript",
  ".ts": "TypeScript", ".tsx": "TypeScript + React",
  ".jsx": "JavaScript + React",
  ".py": "Python",
  ".java": "Java",
  ".rb": "Ruby",
  ".c": "C", ".h": "C/C Header",
  ".cpp": "C++", ".cc": "C++", ".cxx": "C++", ".hpp": "C++ Header",
  ".cs": "C#",
  ".go": "Go",
  ".rs": "Rust",
  ".php": "PHP",
  ".html": "HTML", ".htm": "HTML",
  ".css": "CSS",
  ".json": "JSON",
  ".xml": "XML",
  ".sh": "Shell Script",
  ".zsh": "Zsh Script",
  ".fish": "Fish Shell Script",
  ".bat": "Batch Script",
  ".cmd": "Windows Command Script",
  ".kt": "Kotlin",
  ".swift": "Swift",
  ".lua": "Lua",
  ".pl": "Perl",
  ".pm": "Perl Module",
  ".r": "R",
  ".rmd": "R Markdown",
  ".sql": "SQL",
  ".sqlite": "SQLite DB",
  ".scala": "Scala",
  ".dart": "Dart",
  ".m": "Objective-C / MATLAB",
  ".fs": "F#",
  ".erl": "Erlang",
  ".ex": "Elixir",
  ".exs": "Elixir Script",
  ".clj": "Clojure",
  ".cljs": "ClojureScript",
  ".coffee": "CoffeeScript",
  ".groovy": "Groovy",
  ".nim": "Nim",
  ".v": "V Language",
  ".jl": "Julia",
  ".hx": "Haxe",
  ".vala": "Vala",
  ".ml": "OCaml",
  ".mli": "OCaml Interface",
  ".vb": "VB.NET",
  ".vbs": "VBScript",
  ".as": "ActionScript",
  ".lisp": "Lisp",
  ".scm": "Scheme",
  ".ss": "Scheme",
  ".adb": "Ada",
  ".ads": "Ada Specification",
  ".d": "D Language",
  ".ps1": "PowerShell",
  ".psm1": "PowerShell Module",
  ".rkt": "Racket",
  ".tcl": "Tcl",
  ".tk": "Tcl",
  ".awk": "Awk",
  ".gawk": "Gawk",
  ".tex": "LaTeX",
  ".ltx": "LaTeX",
  ".sty": "LaTeX Style",
  ".cls": "LaTeX Class",
  ".ipynb": "Jupyter Notebook",
  ".md": "Markdown",
  ".markdown": "Markdown",
  ".toml": "TOML",
  ".yaml": "YAML",
  ".yml": "YAML",
  ".ini": "INI",
  ".cfg": "Config File",
  ".conf": "Config File",
  ".properties": "Java Properties",
  ".env": "Environment Config",
  ".dockerfile": "Dockerfile",
  ".docker": "Dockerfile",
  ".gitignore": "Git Ignore",
  ".gitattributes": "Git Attributes",
  ".makefile": "Makefile",
  ".mk": "Makefile",
  ".cmake": "CMake",
  ".gradle": "Gradle",
  ".pom": "Maven POM XML",
  ".xml.dist": "XML",
  ".xaml": "XAML",
  ".qml": "QML",
  ".sol": "Solidity",
  ".zig": "Zig",
  ".cr": "Crystal",
  ".bf": "Brainfuck",
  ".eml": "Email Source",
  ".csv": "CSV",
  ".tsv": "TSV",
  ".log": "Log File",
  ".bat": "Batch",
  ".cmd": "Command Script",
  ".psd1": "PowerShell Data File",
  ".psm1": "PowerShell Module",
  ".lql": "LogiQL",
  ".mlir": "MLIR",
  ".vue": "Vue Component",
  ".tsx": "TypeScript + JSX",
  ".lock": "Lock File",
  ".twig": "Twig Template",
  ".mustache": "Mustache Template",
  ".hbs": "Handlebars Template",
  ".ejs": "EJS Template",
  ".jade": "Pug Template",
  ".pug": "Pug Template",
  ".haml": "Haml Template",
  ".slim": "Slim Template",
  ".liquid": "Liquid Template",
  ".jsp": "Java Server Pages",
  ".jspx": "Java Server Pages XML",
  ".asp": "ASP Script",
  ".aspx": "ASP.NET",
  ".vbhtml": "ASP.NET Razor",
  ".cshtml": "ASP.NET Razor",
  ".jspf": "Java Server Page Fragment",
  ".xhtml": "XHTML",
  ".ssjs": "Server-side JavaScript",
  ".cfc": "ColdFusion Component",
  ".cfm": "ColdFusion Markup",
  ".mdx": "Markdown with JSX",
  ".ipynb": "Jupyter Notebook",
  ".scala.html": "Play Framework Template",
  ".erl": "Erlang",
  ".hrl": "Erlang Header",
  ".ex": "Elixir",
  ".exs": "Elixir Script",
  ".edn": "Clojure Data",
  ".edn": "Extensible Data Notation",
  ".apib": "API Blueprint",
  ".asciidoc": "AsciiDoc",
  ".adoc": "AsciiDoc",
  ".pod": "Perl POD",
  ".rst": "reStructuredText",
  ".rest": "reStructuredText",
  ".adb": "Ada Body",
  ".ads": "Ada Specification",
  ".dot": "Graphviz DOT",
  ".gv": "Graphviz DOT",
  ".graphql": "GraphQL",
  ".gql": "GraphQL",
  ".hs": "Haskell",
  ".lhs": "Literate Haskell",
  ".erl": "Erlang",
  ".dylib": "Dynamic Library",
  ".lib": "Library File",
  ".a": "Static Library",
  ".so": "Shared Object",
  ".dll": "Dynamic Link Library",
  ".pdb": "Program Database",
  ".obj": "Object File",
  ".o": "Object File",
  ".class": "Java Class File",
  ".jar": "Java Archive",
  ".war": "Web Application Archive",
  ".ear": "Enterprise Archive",
  ".apk": "Android Package",
  ".ipa": "iOS App Archive",
  ".xpi": "Mozilla Firefox Add-on",
  ".crx": "Chrome Extension",
  ".vsix": "Visual Studio Extension",
  ".nupkg": "NuGet Package",
  ".gem": "Ruby Gem",
  ".whl": "Python Wheel",
  ".egg": "Python Egg",
  ".tar": "Tarball Archive",
  ".gz": "Gzip Archive",
  ".bz2": "Bzip2 Archive",
  ".xz": "XZ Archive",
  ".zip": "ZIP Archive",
  ".rar": "RAR Archive",
  ".7z": "7-Zip Archive",
  ".lz": "Lzip Archive",
  ".lzma": "LZMA Archive",
  ".z": "Compress Archive",
  ".cab": "Cabinet Archive",
  ".iso": "ISO Disk Image",
  ".img": "Disk Image",
  ".dmg": "Mac OS Disk Image",
  ".vhd": "Virtual Hard Disk",
  ".vmdk": "VMware Disk",
  ".qcow2": "QEMU Copy On Write Disk",
  ".vdi": "VirtualBox Disk",
  ".ova": "Open Virtual Appliance",
  ".ovf": "Open Virtualization Format",
  ".box": "Vagrant Box",
  ".torrent": "BitTorrent File",
  ".m3u": "M3U Playlist",
  ".pls": "PLS Playlist",
  ".xspf": "XSPF Playlist",
  ".cue": "Cue Sheet",
  ".log": "Log File",
  ".conf": "Configuration File",
  ".props": "Properties File",
  ".rc": "Resource Script",
  ".resx": "Resource XML",
  ".manifest": "Application Manifest",
  ".pem": "Privacy Enhanced Mail",
  ".key": "Private Key",
  ".crt": "Certificate",
  ".csr": "Certificate Signing Request",
  ".der": "DER Certificate",
  ".p12": "PKCS#12 Archive",
  ".pfx": "PKCS#12 Archive",
  ".jks": "Java KeyStore",
  ".kdb": "Key Database",
  ".asc": "ASCII Armor",
  ".gpg": "GnuPG Encrypted File",
  ".sig": "Signature File",
  ".apk": "Android Package",
  ".aab": "Android App Bundle",
  ".ipa": "iOS Archive",
  ".app": "Mac Application",
  ".exe": "Windows Executable",
  ".dll": "Windows DLL",
  ".bat": "Batch Script",
  ".cmd": "Command Script",
  ".msi": "Windows Installer",
  ".ps1": "PowerShell Script",
  ".psm1": "PowerShell Module",
  ".psd1": "PowerShell Data File",
  ".vbs": "VBScript",
  ".wsf": "Windows Script File",
  ".ws": "Windows Script",
  ".msc": "Microsoft Management Console",
  ".scr": "Windows Screen Saver",
  ".sys": "Windows System File",
  ".drv": "Windows Driver",
  ".fon": "Windows Font",
  ".icns": "Mac Icon File",
  ".ico": "Icon File",
  ".icns": "Mac OS X Icon File",
  ".svg": "Scalable Vector Graphics",
  ".eps": "Encapsulated PostScript",
  ".ps": "PostScript",
  ".ai": "Adobe Illustrator",
  ".pdf": "Portable Document Format",
  ".doc": "Microsoft Word Document",
  ".docx": "Microsoft Word Open XML Document",
  ".xls": "Microsoft Excel Spreadsheet",
  ".xlsx": "Microsoft Excel Open XML Spreadsheet",
  ".ppt": "Microsoft PowerPoint Presentation",
  ".pptx": "Microsoft PowerPoint Open XML Presentation",
  ".odt": "OpenDocument Text",
  ".ods": "OpenDocument Spreadsheet",
  ".odp": "OpenDocument Presentation",
  ".rtf": "Rich Text Format",
  ".txt": "Text File",
  ".md": "Markdown",
  ".log": "Log File",
  ".csv": "Comma-separated Values",
  ".tsv": "Tab-separated Values",
  ".ics": "iCalendar File",
  ".vcf": "vCard File",
  ".ics": "Calendar File",
  ".ical": "iCal File",
  ".icalendar": "iCalendar File",
  ".icsv": "Comma-separated Values",
  ".ini": "Initialization File",
  ".cfg": "Configuration File",
  ".conf": "Configuration File",
  ".bat": "Batch File",
  ".cmd": "Command File",
  ".sh": "Shell Script",
  ".bash": "Bash Script",
  ".zsh": "Zsh Script",
  ".fish": "Fish Shell Script",
  ".ps1": "PowerShell Script",
  ".psm1": "PowerShell Module",
  ".vbs": "VBScript",
  ".wsf": "Windows Script File",
  ".msc": "Microsoft Management Console",
  ".scr": "Windows Screen Saver",
  ".sys": "Windows System File",
  ".drv": "Windows Driver",
  ".exe": "Windows Executable",
  ".dll": "Windows DLL",
  ".app": "Mac Application",
  ".dmg": "Mac Disk Image",
  ".pkg": "Mac Installer Package",
  ".rpm": "Red Hat Package Manager",
  ".deb": "Debian Package",
  ".tar.gz": "Tarball Gzip Archive",
  ".tar.bz2": "Tarball Bzip2 Archive",
  ".tar.xz": "Tarball XZ Archive",
  ".7z": "7-Zip Archive",
  ".rar": "RAR Archive",
  ".zip": "ZIP Archive",
  ".gz": "Gzip Archive",
  ".bz2": "Bzip2 Archive",
  ".xz": "XZ Archive",
  ".lzma": "LZMA Archive",
  ".lz": "Lzip Archive",
  ".z": "Compress Archive",
  ".cab": "Cabinet Archive",
  ".iso": "ISO Disk Image",
  ".img": "Disk Image",
  ".vhd": "Virtual Hard Disk",
  ".vmdk": "VMware Disk Image",
  ".qcow2": "QEMU Disk Image",
  ".vdi": "VirtualBox Disk Image",
  ".ova": "Open Virtual Appliance",
  ".ovf": "Open Virtualization Format",
  ".box": "Vagrant Box",
  ".torrent": "BitTorrent File",
  ".m3u": "M3U Playlist",
  ".pls": "PLS Playlist",
  ".xspf": "XSPF Playlist",
  ".cue": "Cue Sheet",
  ".log": "Log File"
};


function detectLanguage(filename) {
  const ext = filename.slice(filename.lastIndexOf('.')).toLowerCase();
  return langMap[ext] || "不明な言語（未定義）";
}

function checkDangerous(code) {
  return dangerPatterns.filter(p => p.test(code));
}

analyzeBtn.addEventListener('click', async () => {
  summary.innerHTML = "";
  dangerList.innerHTML = "";
  resultContainer.classList.remove('hidden');

  const files = fileInput.files;
  let langCount = {};
  let totalSize = 0;
  let combinedCode = codeInput.value || "";

  for (let file of files) {
    const content = await file.text();
    combinedCode += "\n" + content;
    totalSize += file.size;
    const lang = detectLanguage(file.name);
    langCount[lang] = (langCount[lang] || 0) + 1;
  }

  if (codeInput.value) {
    langCount["貼り付けコード"] = (langCount["貼り付けコード"] || 0) + 1;
  }

  const dangerHits = checkDangerous(combinedCode);

  summary.innerHTML = `
    <p><strong>ファイル数：</strong>${files.length}</p>
    <p><strong>総容量：</strong>${(totalSize / 1024).toFixed(2)} KB</p>
    <p><strong>言語検出：</strong></p>
    <ul>
      ${Object.entries(langCount).map(([lang, count]) =>
        `<li>${lang}: ${count}個</li>`
      ).join("")}
    </ul>
  `;

  if (dangerHits.length > 0) {
    dangerList.innerHTML = `
      <div class="danger">
        <strong>不審なコードパターンを検出：</strong>
        <ul>
          ${dangerHits.map(p => `<li><code>${p}</code></li>`).join("")}
        </ul>
      </div>
    `;
  } else {
    dangerList.innerHTML = `<p>不審なコードは特に検出されませんでした。</p>`;
  }
});
